### ISSUE TITLE
Application language sets to Chinese and not possible to change?

### ISSUE THREAD

**Issue by laurent22** [pilotmoon/Scroll-Reverser#109]
My operating system is in French and it seems the app picks Chinese as default language. It should instead pick English as default.

Also it looks like once the language is set it's not possible to change it?

![image](https://user-images.githubusercontent.com/1285584/104724610-d2179000-5728-11eb-9b4b-84352c6a54eb.png)

**Comment by invariant** [comment]
Can you check your Language & Region system prefs. There should be a list of preferred languages. Ensure that English is set higher precedence than Chinese (see screenshot).

If not can you send me a screen shot of      your own settings, it may help me understand the issue.

![CleanShot 2021-01-15 at 16 43 37@2x](https://user-images.githubusercontent.com/17520/104754298-f5eecc00-5750-11eb-9d2e-1bda78b5662c.png)

**Comment by invariant** [comment]
(By the way, we now have a French translation which will ship with the next update!)

**Comment by laurent22** [comment]
Indeed I had Chinese in the list without realising it, probably because I've tested pinyin input not long ago. So the behaviour actually makes sense, and I'm going to add English to the list to avoid this kind of issue in the future. Thanks for the info!

![image](https://user-images.githubusercontent.com/1285584/104762770-cf369280-575c-11eb-8c29-cd7341ca1ce6.png)
