### ISSUE TITLE
Installation process

### ISSUE THREAD

**Issue by asetmumin99** [pilotmoon/Scroll-Reverser#116]
I'm new to mac os and recently bought a macbook with m1.
I found that there is no guidance in the readme about the actual installation process, unless I'm blind, of course.

After I've cloned the repo, what should I do? 
Thanks for your time and effort.

**Comment by invariant** [comment]
Hi. If you would like to simply use Scroll Reverser, download the zip file of the [latest release](https://github.com/pilotmoon/Scroll-Reverser/releases/tag/v1.8). (You can also find this at https://pilotmoon.com/scrollreverser/.)Then unzip it, pop it in your Application fiolder, and run.

If you are looking to build it from source yourself you will need Xcode. Happy to help with any more detailed queries.
