### ISSUE TITLE
Both trackpad and  mice are reversed

### ISSUE THREAD

**Issue by codren** [pilotmoon/Scroll-Reverser#119]
I only checked the reverse vertical , reverse mouse checkbox and set both input monitoring and accessibility settings. but when I press the enable button, both are equally reversed

I'm using M1 MacBook Air. big sur version 11.2.3

Can you tell me the solution?

**Comment by invariant** [comment]
Hi, can you please option(⌥)-click the Scroll Reverser menu bar icon, this will bring up a debug window. Then do some scrolling with the trackpad to produce some debug output. Then pause the window, copy and paste to me. Thanks!

**Comment by codren** [comment]
Thank you for your quick response !  Here is the debug output using the trackpad.

`22:18:05.7 Log started [on yes][v yes][h no][trackpad no][mouse yes]
22:18:29.3 0 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377262][pid 0][x 0][y 0]
22:18:29.4 1 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377326][pid 0][x 0][y -1]
22:18:29.4 2 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377334][pid 0][x 1][y -4]
22:18:29.4 3 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377342][pid 0][x 2][y -6]
22:18:29.4 4 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377350][pid 0][x 2][y -7]
22:18:29.4 5 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377358][pid 0][x 4][y -10]
22:18:29.4 6 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377366][pid 0][x 3][y -10]
22:18:29.4 7 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377374][pid 0][x 3][y -9]
22:18:29.4 8 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377396][pid 0][x 3][y -11]
22:18:29.4 9 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377396][pid 0][x 5][y -16]
22:18:29.4 10 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377397][pid 0][x 4][y -14]
22:18:29.4 11 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377405][pid 0][x 3][y -11]
22:18:29.4 12 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377418][pid 0][x 5][y -15]
22:18:29.5 13 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377421][pid 0][x 4][y -11]
22:18:29.5 14 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377429][pid 0][x 4][y -11]
22:18:29.5 15 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377437][pid 0][x 3][y -9]
22:18:29.5 16 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377445][pid 0][x 3][y -9]
22:18:29.5 17 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377466][pid 0][x 2][y -7]
22:18:29.5 18 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377467][pid 0][x 3][y -7]
22:18:29.5 19 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377469][pid 0][x 2][y -7]
22:18:29.5 20 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377477][pid 0][x 2][y -5]
22:18:29.5 21 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377485][pid 0][x 2][y -3]
22:18:29.5 22 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377493][pid 0][x 2][y -4]
22:18:29.5 23 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377501][pid 0][x 1][y -3]
22:18:29.5 24 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377509][pid 0][x 1][y -2]
22:18:29.5 25 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377517][pid 0][x 1][y -2]
22:18:29.6 26 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377535][pid 0][x 1][y -1]
22:18:29.6 27 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377535][pid 0][x 1][y -1]
22:18:29.6 28 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377540][pid 0][x 1][y -1]
22:18:29.6 29 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24377605][pid 0][x 0][y 0]
22:18:33.2 30 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381213][pid 0][x 0][y 0]
22:18:33.3 31 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381221][pid 0][x 0][y 2]
22:18:33.3 32 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381229][pid 0][x -1][y 3]
22:18:33.3 33 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381237][pid 0][x -1][y 3]
22:18:33.3 34 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381245][pid 0][x -1][y 3]
22:18:33.3 35 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381253][pid 0][x -1][y 5]
22:18:33.3 36 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381261][pid 0][x -1][y 5]
22:18:33.3 37 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381284][pid 0][x -1][y 7]
22:18:33.3 38 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381284][pid 0][x -1][y 5]
22:18:33.3 39 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381285][pid 0][x -1][y 7]
22:18:33.3 40 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381293][pid 0][x -1][y 6]
22:18:33.3 41 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381306][pid 0][x -1][y 7]
22:18:33.3 42 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381309][pid 0][x -1][y 8]
22:18:33.3 43 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381316][pid 0][x -1][y 5]
22:18:33.4 44 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381324][pid 0][x -1][y 6]
22:18:33.4 45 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381332][pid 0][x -1][y 6]
22:18:33.4 46 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381354][pid 0][x -1][y 6]
22:18:33.4 47 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381354][pid 0][x -1][y 6]
22:18:33.4 48 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381357][pid 0][x -1][y 6]
22:18:33.4 49 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381368][pid 0][x -1][y 6]
22:18:33.4 50 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381372][pid 0][x -1][y 5]
22:18:33.4 51 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381380][pid 0][x -1][y 5]
22:18:33.4 52 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381388][pid 0][x 0][y 3]
22:18:33.4 53 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381396][pid 0][x -1][y 4]
22:18:33.4 54 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381404][pid 0][x -1][y 3]
22:18:33.5 55 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381423][pid 0][x -1][y 3]
22:18:33.5 56 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381424][pid 0][x -1][y 3]
22:18:33.5 57 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381428][pid 0][x 0][y 3]
22:18:33.5 58 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381436][pid 0][x -1][y 2]
22:18:33.5 59 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381444][pid 0][x 0][y 2]
22:18:33.5 60 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381452][pid 0][x -1][y 2]
22:18:33.5 61 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381460][pid 0][x 0][y 1]
22:18:33.5 62 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381468][pid 0][x 0][y 1]
22:18:33.5 63 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381492][pid 0][x -1][y 1]
22:18:33.5 64 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381492][pid 0][x 0][y 1]
22:18:33.5 65 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381492][pid 0][x 0][y 1]
22:18:33.6 66 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 24381524][pid 0][x 0][y 0]
22:18:41.2 Log paused [on yes][v yes][h no][trackpad no][mouse yes]
`

**Comment by codren** [comment]
I just saw #92 and solved the problem.  I'm sorry  that I asked you this question without looking any further.  I'll use it well :)

**Comment by invariant** [comment]
That's OK 👍 I should have remembered to mention that as well.
