### ISSUE TITLE
Add settings for scroll momentum

### ISSUE THREAD

**Issue by jzju** [pilotmoon/Scroll-Reverser#121]

**Comment by invariant** [comment]
Thanks - can you describe in more detail the functionality you are looking for?

**Comment by jzju** [comment]
![Screenshot 2021-04-19 at 11 34 54](https://user-images.githubusercontent.com/9774380/115215810-281f1980-a104-11eb-9733-8dab6352fb83.jpg)

Sorry I used the wrong word it's called inertia.

What that does is that if you flick your fingers on the touchpad the page will scroll depending on how fast you flick. But with mouse I prefer that the scroll distance is independent of scroll speed, one click should be a fixed number of lines.

**Comment by jzju** [comment]
I may have been mistaken after closer testing, it's that apple animations make the scrolling feel wobbly and not the settings itself.

**Comment by invariant** [comment]
Aha I think I get it. So if you are using a wheel mouse with a step-by-step scroll, you might want to go into Scroll Reverser settings and turn on beta updates and get the latest beta. This has a setting to set the step size which might be just what you are looking for.

**Comment by jzju** [comment]
The beta step size works perfectly!

**Comment by invariant** [comment]
Awesome - thanks for the feedback

**Comment by jzju** [comment]
This settings fixed the mouse problem but could you make a toggle to let the trackpad keep the default behavior?

**Comment by invariant** [comment]
Thye step size slider should only be affecting the mouse wheel and not trackpads. What kind of trackpad are you using?

**Comment by jzju** [comment]
Sorry I forgot that I disabled the inertia in settings.

**Comment by invariant** [comment]
Ahah - I was just thinking of suggesting that. No worries
