### ISSUE TITLE
Stop re-enabling menulet on launch

### ISSUE THREAD

**Issue by mcandre** [pilotmoon/Scroll-Reverser#122]
When Scroll Reverser is not presently running, then I expect a fresh launch to honor the persisted settings and NOT appear in the menu bar, unless I explicitly configured it to do so.

When Scroll Reverser is already running, then I would expect a relaunch to show the configuration panel. Again, no menubar icon should appear unless I configured the application to show an icon.

**Comment by invariant** [comment]
Thanks for reporting. In a quick test just now, I can't seem to reproduce this but I may be doing things in a different way. (I'm hiding from menu bar, quitting via Activity Monitor, then relaunching from Finder.)

Could you give me some more detailed steps to reproduce, along with version numbers? Cheers.

**Comment by invariant** [comment]
Thinking about it I guess you may really be referring to *re*launching while already running? That is, on first launch with the "Show in menu bar" deselected, it will honor the setting (in my testing). But relaunching while already running in this menu-hidden state re-enables the menu bar. And I think what you are saying is it would be better just to go directly to the preferences window without re-showing in the menu bar icon.

**Comment by invariant** [comment]
OK, re-reading again I think that is exactly what you were saying in the first place, so please disregard the previous two comments. 🙃

**Comment by invariant** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Relaunch to show prefs directly.](https://trello.com/c/wRs62L2G/37-relaunch-to-show-prefs-directly)

**Comment by pilotmoon** [comment]
Implemented in beta [Build 10519](https://github.com/pilotmoon/Scroll-Reverser/releases/tag/b10519).
