### ISSUE TITLE
Scroll Reverser changes scroll direction suddenly

### ISSUE THREAD

**Issue by AnUntitledAccount** [pilotmoon/Scroll-Reverser#128]
I use Scroll Reverser to play Minecraft on a Mac since switching through the hotbar is more intuitive. However, the scroll direction reverses every few minutes which always throws me off. For example, when I launch Scroll Reverser, it does its job but then a few minutes later, it goes back to the default scroll setting. Then, a few minutes later, it starts working again.

Is there any way to fix this?

**Comment by invariant** [comment]
Well it's certainly not supposed to do that! Can you tell me more about your set up - what input device are you using to play, and what checkboxes do you have set in Scroll Reverser prefs?

**Comment by AnUntitledAccount** [comment]
I use a [cheap generic branded mouse](https://www.officeworks.com.au/shop/officeworks/p/j-burrows-wired-optical-mouse-black-jbm739wmbk). The settings are set to default and I'm currently using the latest version (1.8.1). My OS is macOS Big Sur 11.5.2 and I play on Minecraft 1.8.9 (modded). I also have Karabiner Elements 13.7.0 but none of the settings that run on it should affect the scrolling. The only option set in the application is switching Ctrl+Left Click to just Left Click.
![Screen Shot 2021-10-03 at 7 06 28 pm](https://user-images.githubusercontent.com/50532251/135745435-66695251-c465-4428-935a-f07df2f26df0.png)

**Comment by AnUntitledAccount** [comment]
Seems like Scroll Reverser is working as intended. It seems to be isolated in Minecraft after further digging.
