### ISSUE TITLE
Scroll Reverser jumps from backward and forward scrolling when using trackpad

### ISSUE THREAD

**Issue by ravenspired** [pilotmoon/Scroll-Reverser#131]
Scroll Reverser jumps from backward and forward scrolling when using trackpad. This issue appeared after upgrading to macOS Monterey. It happens randomly for brief amounts of time. I only observed it when scrolling downward. Using M1 Macbook Pro (2020)
Thank you

**Comment by mrcsilva** [comment]
Isn't this a duplicate of #129? I'm also seeing that problem and I think they already discussed that problem on that issue.

**Comment by invariant** [comment]
Thanks for reporting @ravenspired, and thanks @mrcsilva - this is indeed a dupe of #129 so I will close this one
