### ISSUE TITLE
1.8.1 Release is missing the .zip under Assets

### ISSUE THREAD

**Issue by HunterTTP** [pilotmoon/Scroll-Reverser#133]
1.8.1 Release is missing the .zip under Assets which holds the .app needed for install.

Current:

<img width="895" alt="Screen Shot 2021-12-06 at 9 51 09 PM" src="https://user-images.githubusercontent.com/11375502/144957358-6636a552-2b60-484a-977c-e70191ab6a54.png">

Previous build:

<img width="935" alt="Screen Shot 2021-12-06 at 9 52 41 PM" src="https://user-images.githubusercontent.com/11375502/144957817-ad271d5e-a681-44af-8571-3c9506cb4695.png">

**Comment by enrichman** [comment]
I came to say this. I have just downloaded the 1.8 and updated from itself.

**Comment by invariant** [comment]
Fixed 👍
