### ISSUE TITLE
update the APP icon for new design of macos

### ISSUE THREAD

**Issue by BrightVan** [pilotmoon/Scroll-Reverser#146]
here is a example from [macosicons.com](https://media.macosicons.com/parse/files/macOSicons/0a05352968d8cea6c8ce9649dc95c538_Scroll_Reverser.icns)

![image](https://user-images.githubusercontent.com/9381559/179506697-3ef575fb-b785-4728-acd3-94c144618b3c.png)

**Comment by pilotmoon** [comment]
Done in [Build 10519](https://github.com/pilotmoon/Scroll-Reverser/releases/tag/b10519).
