### ISSUE TITLE
Stops working after woke-up from sleep

### ISSUE THREAD

**Issue by rafiqrahim** [pilotmoon/Scroll-Reverser#15]
I have a 2013 MBA with OSX 10.10.2. This problem happens after the 10.10.2 update.
I am using v1.7.1 of Scroll Reverser and have "Reverse Trackpad" checked out in the settings.
After waking up the MBA from several hours of sleep, the trackpad reverse effect stop working.
Restarting Scroll Reverser will fix this problem.

**Comment by nbppp2** [comment]
I am also seeing a similar issue. When waking from sleep, it reverses the trackpad, although it is unchecked. Restarting does fix the problem.

**Comment by inod** [comment]
Related issue: I have only "reverse mouse" checked.

After wake up:
- the mouse is reverted (OK, as it should be) 
- the trackpad also is reverted (it shouldn't).

**Comment by levic** [comment]
Also happens on a retina macbook pro 2015 10.10.5; works fine after a reboot, but then when it goes to sleep after waking the trackpad now does whatever the mouse settings are set to.

**Comment by NHDaly** [comment]
+1 on a 13" MacBook Air, Early 2014, OS 10.10.5 (14F27).

**Comment by hansbogert** [comment]
Not sure if +1 are appreciated, but:
+1 on a 13" MacBook Air, 2012, OS 10.11

**Comment by harinsa** [comment]
+1 on 13" MBP Early 2015 10.11.1

**Comment by JDoucette** [comment]
+1 on MacBook Pro (13-inch, Early 2015)
OS v10.11.3

**Comment by AdamGerthel** [comment]
+1 Macbook Air (11-inch, mid 2013).
OS v10.11.6

**Comment by KevinBlom** [comment]
This problem seems to happen on macOS Sierra as well. A reboot of the OS fixes it.

**Comment by 16patsle** [comment]
I can confirm that this issue with the trackpad often being reversed after woking from sleep. It is occuring on my MBP (2015 model) with Sierra. Restarting the app seems to solve it for me.

**Comment by invariant** [comment]
Ref: **[Conversation #5255](https://secure.helpscout.net/conversation/268850053/5255) / Markus**
