### ISSUE TITLE
When using three finger to move between full screen applications, the reverser seems to unable to handle it

### ISSUE THREAD

**Issue by Jane42070** [pilotmoon/Scroll-Reverser#152]
<img width="642" alt="image" src="https://user-images.githubusercontent.com/45375971/191442418-95355d9e-6524-422a-bc2f-8380df22db59.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/45375971/191443359-3633fd8b-bda6-46c1-9210-228b9a3b2d8c.png">
<img width="780" alt="image" src="https://user-images.githubusercontent.com/45375971/191443495-01be942f-fd34-424b-93e4-89ed6575d19b.png">
This is my personal config
Using two finger browsing web is fine

**Comment by invariant** [comment]
That reverses, scoring, but not other gestures
