### ISSUE TITLE
Not starting at login

### ISSUE THREAD

**Issue by mphist** [pilotmoon/Scroll-Reverser#161]
Scroll Reverser is not starting at login for me. Does anyone have the same issue? Running on macOS Ventura 13.0.1

<img width="390" alt="image" src="https://user-images.githubusercontent.com/18204788/210601544-894a148b-a42e-493d-829a-61c7b539bc2d.png">

<img width="479" alt="image" src="https://user-images.githubusercontent.com/18204788/210601732-40b3a047-eb0a-48ce-8f91-0acf7c630411.png">

**Comment by pilotmoon** [comment]
Not sure why it would happen, but I suggest to try removing and re-add it to the login items, and also ensuring that Scroll Reverser is in the Applications folder and that there aren't any additional copies of it on the disk.

**Comment by mphist** [comment]
> Not sure why it would happen, but I suggest to try removing and re-add it to the login items, and also ensuring that Scroll Reverser is in the Applications folder and that there aren't any additional copies of it on the disk.

Scroll Reverser was in Downloads and not in Applications. Relocating it solved the issue. Thanks! 😊

**Comment by streetsoul00** [comment]
Scroll reverser is not starting at login for me.
The app shown on the list is not having app icon.
Mac OS Sonoma 14.3
![image](https://github.com/pilotmoon/Scroll-Reverser/assets/157815063/6dc4a3db-7605-4a2d-87c7-540d6fcc1308)
![Screenshot 2024-01-26 at 7 44 08 PM](https://github.com/pilotmoon/Scroll-Reverser/assets/157815063/a3f360aa-9bf4-4d34-983d-d38838a73e22)

**Comment by mgarort** [comment]
I can confirm that the issue was solved for me in the same way: by placing the app in the `Applications` folder rather than the `Downloads` folder. Thank you!
