### ISSUE TITLE
Scroll not reversed only in Calendar app

### ISSUE THREAD

**Issue by demacdo** [pilotmoon/Scroll-Reverser#163]
I've come across a bug--Scroll Reverser doesn't seem to work in the Mac Calendar app, but works fine everywhere else. It's been like this for a few months now, but I'm pretty sure that it worked fine in Calendar previously.

Currently using Scroll Reverser version 1.8.2, and the bug appears on both a 16 inch MacBook Pro M1 Pro (2021) as well as a 14 inch MacBook Pro M1 Max (2021), both on Ventura 13.1.

**Comment by pilotmoon** [comment]
This one is a long-standing "can't fix". It does not and cannot work in the Calendar app. It's because of the way the Calendar app detects scrolling. It uses gestures only and ignores scrolling events.
