### ISSUE TITLE
'Look up' feature (tap with three fingers) is disabled

### ISSUE THREAD

**Issue by lamphanviet** [pilotmoon/Scroll-Reverser#17]
The Look up (tap with three fingers) feature doesn't work when Scroll Reverser is running. I quit Scroll Reverser and it works again. There must be a bug here with Scroll Reverser.

**Comment by greengiraffe** [comment]
I can confirm this issue on OS X 10.10.2

**Comment by invariant** [comment]
Closed as dupe of #1.

Good news is I've found a fix  🎉😃
