### ISSUE TITLE
not responding state after upgrading MacOS to 14.2

### ISSUE THREAD

**Issue by aminmesbahi** [pilotmoon/Scroll-Reverser#173]
Since I updated my machine to 14.2, the Scroll-Reverser not worked, and in the activity monitor, I see it is in the **not responding** state

Machine: MBP 16" M2 Pro
OS: MacOS 14.2

**Comment by pilotmoon** [comment]
What remedial steps have you already tried?

If not already, try force quitting it and launch again.

**Comment by aminmesbahi** [comment]
- Remove, then install again
- check the console log to find a probable clue
- Restart the machine :D

**Comment by aminmesbahi** [comment]
Ah! weird issue!!
With unpair/pair mouse again, Fixed! 
thanks
