### ISSUE TITLE
New icon is slightly too large

### ISSUE THREAD

**Issue by Stanzilla** [pilotmoon/Scroll-Reverser#180]
hey there, just tested the pre-release and saw that the new icon is slightly too large

![CleanShot-2024-06-20-02 40 53](https://github.com/pilotmoon/Scroll-Reverser/assets/75278/c86108ca-698e-4b31-8049-2db769d8d95a)

there are some Apple design guidelines about margins that probably need to be adhered to

**Comment by pilotmoon** [comment]
Thank you! I've re-made the icon with the correct dimensions. (e4a8c22)
