### ISSUE TITLE
Scroll Reverser triggers issue with disabling click on Allow button in Keychain popups

### ISSUE THREAD

**Issue by SebastianOsinski** [pilotmoon/Scroll-Reverser#24]
Hi, I know that title seems weird, but here is more detailed description of this issue: http://apple.stackexchange.com/a/212446. Post isn't about Scroll Reverser, but it seems to trigger the same problem. I had said problem with the popup in SourceTree application. Turning off Scroll Reverser fixed the problem.

**Comment by SystemDisc** [comment]
Adding Scroll Reverser to the Accessibility list should fix this (drag the app into the list). Let me know.
<img src="https://i.imgur.com/31nYo0R.png">

**Comment by levic** [comment]
This seems to be a duplicate of #26 

In 10.11.1 (Oct 21 2015) Apple disabled intercepted mouse events to prevent a security vulnerability. In particular this was a problem for remote desktop apps. [ref](https://apple.stackexchange.com/questions/212622/keychain-wont-let-copy-passwords-after-10-11-1-update/213099#213099)

In 10.11.5 (May 16 2016) was released. This allowed intercepted mouse events but triggered a second confirmation requiring the user's password. [ref](https://support.realvnc.com/Knowledgebase/Article/View/518/2/issue-with-keychain-access-on-mac-os-x-10111-el-capitan)

@SebastianOsinski is this ticket still relevant?

**Comment by invariant** [comment]
Closed as now addressed in #26.
