### ISSUE TITLE
Scrolling not reversed for volume slider

### ISSUE THREAD

**Issue by Apanatshka** [pilotmoon/Scroll-Reverser#25]
When you use scrolling to adapt the volume (the slider from the menu bar), the scrolling is not reversed.

**Comment by Apanatshka** [comment]
My workaround for now is to turn off "natural scroll direction" in the mouse settings and reverse the *trackpad* in scroll reverser instead of reversing the scrolling for my mouse.

**Comment by invariant** [comment]
Thank you for posting the workaround.

Volume sliders and the like are a tricky area. I don't plan on doing anything about them.
