### ISSUE TITLE
Trackpad reversing at all times, irrespective of "Reverse Trackpad" setting

### ISSUE THREAD

**Issue by invariant** [pilotmoon/Scroll-Reverser#27]
Reported to me via email.
> Hi. Your apps is the best :) but not work on public beta sierra :(
> ok i resetsrt computer and test, but i use mouse logitech, no apple with normal scroll
> i restart computer but i still i have problem. natrula scroll not work on trackpad when i have enable revers scroll"
<img width="423" alt="pastedgraphic-2" src="https://cloud.githubusercontent.com/assets/17520/20302014/93f63daa-ab1d-11e6-82e7-dcf74e298608.png">

**Comment by basicide** [comment]
Can't see the conversation but I also noticed this issue after the Sierra upgrade. Seems like the Reverse Mouse option reverses the Trackpad right now as well.

**Comment by invariant** [comment]
@basicide, can you try openin the debug console by ⌥-clicking the Scroll Reverser menu bar icon. What output are you seeing with trackpad, and what are you seeing with mouse? You could copy and paste some output here. Please annotate sections of it with what input device it pertains to.

**Comment by invariant** [comment]
I have edited the issue title. I believe this is a general issue rather than a Sierra-specific one. In my own testing, Scroll Reverser is working fine on Sierra.

**Comment by invariant** [comment]
This issue is probably a dupe of #23

**Comment by ibawolf** [comment]
I'm seeing the same issue, scroll reverser was working great in El Capitan, but once I upgraded to Sierra, the mouse scroll wheel (which is checked in preferences) and the trackpad (which is not checked in preferences) work the same.  Here is a log from the Scroll Reverser Debug Console.  The first 4 entries after the "Log cleared" line was from scrolling down on the mouse scroll wheel, the remainder is from scrolling down with two fingers on the macbook pro's trackpad.

08:15:57.5 Log cleared [on yes][v yes][h no][trackpad no][tablet no][mouse/other yes]
08:15:58.7 175 [type scroll][source mouse][reversing yes][notContinuous yes][phase normal][touching 0][touchElapsed 365974574][pid 0][x 0][y 1]
08:16:00.2 176 [type scroll][source mouse][reversing yes][notContinuous yes][phase normal][touching 0][touchElapsed 365976118][pid 0][x 0][y 1]
08:16:01.0 177 [type scroll][source mouse][reversing yes][notContinuous yes][phase normal][touching 0][touchElapsed 365976870][pid 0][x 0][y 1]
08:16:01.9 178 [type scroll][source mouse][reversing yes][notContinuous yes][phase normal][touching 0][touchElapsed 365977734][pid 0][x 0][y 1]
08:16:05.5 179 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365981382][pid 0][x 0][y 0]
08:16:06.1 180 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365981948][pid 0][x 0][y -1]
08:16:06.1 181 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365981972][pid 0][x 0][y -1]
08:16:06.1 182 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982028][pid 0][x 0][y -1]
08:16:06.2 183 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982042][pid 0][x 0][y -1]
08:16:06.2 184 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982058][pid 0][x 0][y -1]
08:16:06.2 185 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982074][pid 0][x 0][y -1]
08:16:06.2 186 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982085][pid 0][x 0][y -1]
08:16:06.2 187 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982098][pid 0][x 0][y -1]
08:16:06.2 188 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982106][pid 0][x 0][y -1]
08:16:06.2 189 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982114][pid 0][x 0][y -1]
08:16:06.2 190 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982128][pid 0][x 0][y -1]
08:16:06.3 191 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982136][pid 0][x 0][y -1]
08:16:06.3 192 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982154][pid 0][x 0][y -1]
08:16:06.3 193 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982154][pid 0][x 0][y -1]
08:16:06.3 194 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982168][pid 0][x 1][y -1]
08:16:06.3 195 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982176][pid 0][x 0][y -1]
08:16:06.3 196 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982184][pid 0][x 0][y -1]
08:16:06.3 197 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982192][pid 0][x 0][y -1]
08:16:06.3 198 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982231][pid 0][x 0][y -1]
08:16:06.3 199 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982231][pid 0][x 0][y -1]
08:16:06.3 200 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982231][pid 0][x 0][y -1]
08:16:06.4 201 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982232][pid 0][x 0][y -1]
08:16:06.4 202 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982246][pid 0][x 0][y -1]
08:16:06.4 203 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982278][pid 0][x 0][y -1]
08:16:06.8 204 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982664][pid 0][x 0][y 1]
08:16:06.8 205 [type scroll][source mouse][reversing yes][usingTouchElapsed yes][phase normal][touching 0][touchElapsed 365982678][pid 0][x 0][y 0]
08:16:38.8 Log paused [on yes][v yes][h no][trackpad no][tablet no][mouse/other yes]

**Comment by invariant** [comment]
@ibawolf does quitting and restarting Scroll Reverser fix this for you?

**Comment by ibawolf** [comment]
No, I've even rebooted (for other reasons) and the problem still exists.

**Comment by ckoomen** [comment]
I have exactly the same issue that ibawolf has, started after the upgrade to Sierra. Same debug console output

**Comment by invariant** [comment]
@chkoomen is this with the latest Scroll Reverser 1.7.4?

**Comment by ckoomen** [comment]
@invariant I just checked, it was with 1.7.4. I have updated now and the issue is gone.

**Comment by invariant** [comment]
Well that's good, thanks for letting me know.

**Comment by ibawolf** [comment]
My problem is also fixed after the update.  Thanks!  Great tool, Great service.

**Comment by invariant** [comment]
Closing issue as this seems to be fixed based on comments.
