### ISSUE TITLE
Please add an open source license

### ISSUE THREAD

**Issue by vbence** [pilotmoon/Scroll-Reverser#28]
Licensing info can be found neither here nor on the official website. It would be important when used on _work laptops_.

**Comment by invariant** [comment]
Just use it.

**Comment by invariant** [comment]
Will think about it but you shouldn't need an open source license simply to use the compiled binary. On the website I say "Scroll Reverser is completely free of charge" that should cover it.

**Comment by vbence** [comment]
Some companies have approval processes for software. Having a well-known, familiar license like **Apache v2** or **BSD** -- if you don't care about your code being included in proprietary products -- could expedite the process.

**Comment by berezovskyi** [comment]
Well, theoretically it might be illegal for us to fork your code and make PRs.

**Comment by berezovskyi** [comment]
So you should add some license, @invariant, e.g. GPL if you are concerned about somebody reusing your code for commercial purpose. But you might hit problems later if you want to publish your app to App/Mac Store (esp. if you accept PRs after licensing it as GPL, unless you ask everybody to sign a CLA). But I second @vbence, Apache/BSD license could be better.

**Comment by berezovskyi** [comment]
http://softwareengineering.stackexchange.com/questions/148146/open-source-code-with-no-license-can-i-fork-it

**Comment by invariant** [comment]
https://en.wikipedia.org/wiki/License-free_software

**Comment by berezovskyi** [comment]
So you don't want anybody to be allowed to fork the repo?

**Comment by invariant** [comment]
I know I could just slap a BSD on it right now and you would all be happy, but I just don't want to make any legally binding and irrevocable commitment at this time. Sorry to be awkward.

**Comment by berezovskyi** [comment]
Well, I am kind of okay with having a local clone of your repo, I think nobody will complain as long as you're the only person distributing binary builds of the app.

**Comment by invariant** [comment]
Here's what I actually would want to say:

Feel free to clone and modify this for your own private purposes. Also feel free to make changes and make these changes publicly available in source form (including via forking on Github). However I don't want anyone to reattribute modified binaries using the same app name or using my icons or using my name. I would be OK with people distributing binaries as long as they change the name, strip out all my icons, and strip out all references to me or my website. Basically, the version I build and sign and distribute is something that I put my name to. Anything else, I don't want associated with me.

However I have never found an existing license text that says all that, and I have no intention of writing my own license. So I have settled for none at al.

**Comment by vbence** [comment]
You can check out MPL and 3-Clause BSD both of them explicitly states that the original author can not be used to endorse the "forked" product.

My understanding is that this explicit clause in MPL caused Debian to name their modified Mozilla products differently (Iceweasel, Icedove etc.).

**Comment by berezovskyi** [comment]
MPL actually does look interesting, and does not conflict with App Store TOC. Today I learned something :) (also took a look at https://tldrlegal.com/license/mozilla-public-license-2.0-(mpl-2)#summary)

The icons can be left unlicensed, so that the forks won't have any rights to use them.

The only problem is that Scroll Reverser is not a trademark per se, but I think it's not well protected anyway from use by a third party.

**Comment by invariant** [comment]
Thanks all for your input. I am going to close this as an issue for now.

**Comment by invariant** [comment]
Scroll Reverser is now licensed under Apache 2.0. 👻
