### ISSUE TITLE
New version crashes on wake from sleep

### ISSUE THREAD

**Issue by berezovskyi** [pilotmoon/Scroll-Reverser#33]
macOS 10.12.1 (16B2555)

Scroll Reverser 1.7.3

Is there a way for me to gather the debug log?

**Comment by invariant** [comment]
With the debug window open, check Pause, and the the table rows will become selectable and copiable to the clipboard.

**Comment by invariant** [comment]
Or do you mean the crash log? This should be in Console.app.

**Comment by berezovskyi** [comment]
My apologies, I meant crash log.

There is not report for Scroll Reverser. I tried to put the laptop to sleep and wake it, but I couldn't immediately reproduce the issue. But at least twice since the update to the latest version, after the laptop wakes from sleep, there is no Scroll Reverser icon in the menu bar.

Is there a debug build I could install to collect more information? Or I am just not finding the right location where do you write the logs?

**Comment by invariant** [comment]
Oh dear, it sounds like my relaunch code is failing. The relevant commit is:
https://github.com/pilotmoon/Scroll-Reverser/commit/176a2a89290fd5c57bf3ca4b72ef625e2413e89d

If so, it is not actually crashing but simply quitting itself. I wonder if the relaunch script sleep time is too short on your machine for some reason. Or perhaps it's not the timeout but something else. Maybe need a more robust relaunch method...

**Comment by berezovskyi** [comment]
Thanks for a pointer, Nick. I think this code can be improved to wait until the current PID is not active:

```bash
while kill -0 $1 >/dev/null 2>&1
do
    sleep 0.01
done

echo "process '${1}' has exited"
```

other options: http://stackoverflow.com/questions/11425876/bash-using-while-or-until-to-wait-until-a-pid-doesnt-exist

I made a quick test, here is how it works: https://www.youtube.com/watch?v=RM7I7cpe3-8&feature=youtu.be

Never did Obj-C development before, but I try to make PR for this change.
