### ISSUE TITLE
Add dutch translation

### ISSUE THREAD

**Issue by erikhuizinga** [pilotmoon/Scroll-Reverser#35]
I'd like to see a dutch translation. I can translate to dutch, because I'm a native speaker, but I don't know how to contribute to this project. Is there an easy way for me to contribute? If it isn't too much hassle, I'd like to know how to contribute to this project with a few basic instructions for somebody that has never worked with applications for MacOS. Otherwise, I guess a list of translated strings would do, don't you think?

**Comment by invariant** [comment]
Hi, Dutch would be fab.
An easy way is for you to take the attached file and edit it in a text editor.
[Localizable.txt](https://github.com/pilotmoon/Scroll-Reverser/files/587367/Localizable.txt)
Each line is a pair of strings. Leave the string on the left untouched, and edit the string on the right to be Dutch. Then just shoot it back to me.

**Comment by invariant** [comment]
I've incorporated this into a test build: https://github.com/pilotmoon/Scroll-Reverser/releases/tag/1.7.5-pre0

**Comment by erikhuizinga** [comment]
Awesome, thanks for the quick implementation and the merge. I love the app, by the way! Truly essential for users of multiple pointing devices with various scroll directions.
