### ISSUE TITLE
Interfering with "shake to locate cursor"

### ISSUE THREAD

**Issue by invariant** [pilotmoon/Scroll-Reverser#39]
Hi Nick! Your Mac app Scroll Reverser is amazing! I really love it!! And here I just found one minor issue - it goes conflict with the “shake mouse pointer to locate” function in macOS Sierra. It worked without any issue before, only up till macOS Sierra I found that the “shake mouse pointer to locate” does not work when I launch Scroll Reverser. 

My machine is MacBook Air 2014 running macOS Sierra 10.12.1

Hope you can fix this in the next update!

Thank you so much for your contribution to make such fantastic app ;)

(Ref: **[Conversation #5303](https://secure.helpscout.net/conversation/276704356/5303) / Huang**)

**Comment by ttuygun** [comment]
same problem

**Comment by invariant** [comment]
Ref: **[Conversation #5427](https://secure.helpscout.net/conversation/298546805/5427) / Mark**

**Comment by invariant** [comment]
I can't reproduce this issue myself. On my machines, shake-to-locate happily coexists with Scroll Reverser.

**Comment by invariant** [comment]
Affects trackpad, but not mouse.

**Comment by gaelfoppolo** [comment]
Any update?

**Comment by invariant** [comment]
Nothing to report

**Comment by invariant** [comment]
Closing as this has been fixed in v1.7.5.
