### ISSUE TITLE
Don't work in MacOS Sierra

### ISSUE THREAD

**Issue by Cayke** [pilotmoon/Scroll-Reverser#49]
I installed the scroll reserver on my macbook pro running MacOS Sierra 10.12.6 but the app don't work. I tried reboting the system with the app opening on startup, but it dont work either. Anyone knows how to make it work on Sierra?

**Comment by invariant** [comment]
I don't know of any problems on Sierra.

**Comment by mizwardomlank** [comment]
I'm using Sierra too, it's working fine. What is your scroll reserver setting?

**Comment by Cayke** [comment]
I tested with other mouse and it worked.
