### ISSUE TITLE
Start at login is not working for High Sierra 10.13.1 

### ISSUE THREAD

**Issue by honghsien5** [pilotmoon/Scroll-Reverser#53]
Start at login does not work after restarting my computer. The "Start at login" option keeps getting reset.

Scroll Reverser version 1.7.6

**Comment by levic** [comment]
1. If you go into System Preferences -> Users & Groups -> (Your user) -> Login Items, and tick/untick Scroll Reverse -> Start at login then does Scroll Reverser show up in that list? (may take a second or two after you tick it before System Preferences refreshes)

1. Are you using any form of device management? (eg Jamf/Casper, Munki) -- you could have a sysadmin who has a whitelist of Start at Login items and Scroll Reverser isn't on it

1. You're not holding down Shift when logging in? (This will cause Start at Login items to be ignored)

**Comment by Jafferwaffer** [comment]
You should also make sure that `Scroll Reverser` is in you `Applications` folder

**Comment by invariant** [comment]
Closing old issue. Please raise a new report if any problems persist with Scroll Reverser v1.8.
