### ISSUE TITLE
High Sierra (10.13.2 (17C205)) stopped working

### ISSUE THREAD

**Issue by shoguevara** [pilotmoon/Scroll-Reverser#56]
Settings don't affect the mouse and trackpad scrolling direction behaviour anymore for some reason

**Comment by patferguson** [comment]
I upgraded to High Sierra 10.13.3 (Supplemental Update installed 2018-02-26) and seem to now be getting a similar issue on my MacBook Pro (13-inch, 2017). I am running the latest Scroll Reverser version 1.7.6. Looking at my Mac's update history, I was previously running the original High Sierra 10.13.3 update from around 2018-02-02.

Changing the Reverse Mouse setting still seems to work with my Logitech MX Anywhere 2S mouse, though the Reverse Trackpad setting doesn't seem to have any effect on the scroll direction. I don't have a tablet available to test the Reverse Tablet setting.

**Comment by shoguevara** [comment]
Unfortunateley, I cant investigate the issue further, for I switched to Better Touch Tool. Nevertheless thanks alot for the developers work!

**Comment by Rovack** [comment]
I also had the problem where "Reverse Trackpad" did nothing, and "Reverse Mouse" affected both the mouse and the trackpad.
After updating Scroll Reverser to 1.7.6, this seems to have been solved. Not sure if it's really the update that fixed it, or whether the app just needed to be restarted.

**Comment by jj999** [comment]
I found the same problem on MacOS Sierra, but I found a workaround - tick "Reverse Vertical" in Scrolling Axes. That fixed it for me. It seems if none Axes is selected, no reverse happens.

**Comment by invariant** [comment]
I'm closing this old issue to tidy up. If anyone still has this problem with the latest version of Scroll Reverser (v1.8 at the time of writing), please as a fresh issue with details.
