### ISSUE TITLE
Not working 10.14 Mojave

### ISSUE THREAD

**Issue by invariant** [pilotmoon/Scroll-Reverser#57]
Ref: **[Conversation #6696](https://secure.helpscout.net/conversation/595037523/6696) / 王**

**Comment by Woooop** [comment]
same problem

**Comment by ananiy** [comment]
+1

**Comment by ananiy** [comment]
![image](https://user-images.githubusercontent.com/33290601/41959151-c192c7b6-7a1e-11e8-9b4d-2ee7196e20f4.png)
just allow this

**Comment by robmerki** [comment]
If anyone was wondering where that option was, it's in: 

**System Preferences > Security & Privacy > Accessibility**

**Comment by awilliams219** [comment]
@ananiy You are my hero.

**Comment by dominiceden** [comment]
Correct path is *System Preferences > Security & Privacy > Privacy > Accessibility*

**Comment by ben1one** [comment]
Thx!!!!!!!

**Comment by vctcn93** [comment]
> ![image](https://user-images.githubusercontent.com/33290601/41959151-c192c7b6-7a1e-11e8-9b4d-2ee7196e20f4.png)
> just allow this

谢谢老哥，很j8稳～！

**Comment by mrakitin** [comment]
I've tried the above instructions, however nothing appears in the list of the apps. Any ideas?

Also, when I tried to run it from command line, I got a segfault error:
```
Scroll Reverser.app/Contents/MacOS $ ./"Scroll Reverser"
2018-10-29 14:55:52.954 Scroll Reverser[42187:3052717] Scroll Reverser ready. Option-click the Scroll Reverser menu bar icon to show the debug console.
Segmentation fault: 11
```
Is this error related to the lack of permissions? Thanks!

**Comment by gmasonxoom** [comment]
I have the same problem - I am able to add the app to the list, however later it stops working, and the list is blank. Looks like some weird permissions bug in Mojave rather than a problem with Scroll Reverser but unsure how to proceed.

**Comment by Cyberbeni** [comment]
https://github.com/pilotmoon/Scroll-Reverser/blob/master/MouseTap.m#L272
Need a nil check for this variable and show alert instead of crashing.

**Comment by terriblefung** [comment]
The app does not work and adding to accessibility permissions list does nothing to help. The list and all the apps I've added to it remain and do not disappear, its just the Scroll Reverser doesn't work at all ever. Restarted MacBook, disconnected mouse and reconnected, flipped which is natural in native options, toggled reverse scroll on and off, none of these things made a difference.

Running Mojave10.14.5

**Comment by WPrintz** [comment]
From Scroll Reverser home page: https://pilotmoon.com/scrollreverser/

macOS 10.14 Mojave users: To get Scroll Reverser working, please do the following:
1) Go to System preferences → Security & Privacy → Privacy → Accessibility
2) Click the Lock icon and enter your password
3) Enable Scroll Reverser in the list

**Comment by waltertross** [comment]
The point is (at least for me):
it DOES work from the Finder, but NOT from the command line (segfault)

**Comment by invariant** [comment]
I'm closing this old issue. If any problem persists, please file as a new issue with reference to latest version. Thanks all.
