### ISSUE TITLE
Doesn't work on macOS Mojave

### ISSUE THREAD

**Issue by wendkos** [pilotmoon/Scroll-Reverser#59]
Can't get Scroll Reverser to start on macOS Mojave.

**Comment by gillib** [comment]
https://github.com/pilotmoon/Scroll-Reverser/issues/57

there is a solution here!! scroll to the end

**Comment by maxwendkos** [comment]
Oh, great. Thanks!
ᐧ

**Comment by invariant** [comment]
Closing old issue. Please raise a new report if any problems persist.
