### ISSUE TITLE
Does it have a dotfile setting?

### ISSUE THREAD

**Issue by nicu-chiciuc** [pilotmoon/Scroll-Reverser#61]
I'm installing Scroll Reverser using cask and would like to be able to save and reset my settings whenever I reinstall my system. It seems like SR doesn't have any .config file or at least I cannot find one. Would it be possible to set the settings programmatically?

**Comment by Cyberbeni** [comment]
~/Library/Application Support/Preferences/com.pilotmoon.scroll-reverser.plist

**Comment by invariant** [comment]
Closing to tidy up. Thanks @Cyberbeni for the answer!
