### ISSUE TITLE
Build error "Nicholas Moore: no identity found"

### ISSUE THREAD

**Issue by AndreaCallia** [pilotmoon/Scroll-Reverser#64]
Hi @invariant, first of all many thanks for all your work... I am trying to build your project but `codesign` fails when running the following two sh script commands.

    codesign -f -v -s "Developer ID Application: Nicholas Moore" "$SPARKLE_PATH/Resources/finish_installation.app"
    codesign -f -v -s "Developer ID Application: Nicholas Moore" "$SPARKLE_PATH/Versions/A"`

The error message is:

    Developer ID Application: Nicholas Moore: no identity found

Am I doing something wrong or is this some new issue?

**Comment by Cyberbeni** [comment]
You could check code sign on copy in the copy frameworks phase and then remove code signing from the script
