### ISSUE TITLE
macOS Catalina

### ISSUE THREAD

**Issue by iharkh** [pilotmoon/Scroll-Reverser#70]
Separate scroll for touchpad and mouse is no longer working on latest beta macOS Catalina (19A501i). Scroll direction for touchpad and mouse now is always the same in spite of settings in the app preferences.

**Comment by iharkh** [comment]
![image](https://user-images.githubusercontent.com/6583990/61296808-8d353500-a7e3-11e9-8a37-1c46453a798e.png)
Allowing the app to monitor inputs fixed the case.

**Comment by jwvanderbeck** [comment]
Thanks for this.  I was about to dig into the code to find out what broke so this saved me the trouble!

**Comment by jutah76** [comment]
Hi, any news on that? i'm still on Mojave, i'm waiting to upgrade to Catalina mainly because of ScrollReverser.

I'm wondering if with the public release of Catalina and the recent upgrade the situation is still the same. Thanks.

**Comment by jwvanderbeck** [comment]
Just follow the step above and it works fine

**Comment by jutah76** [comment]
Hi, I've just updated but I can't find scroll reverser into "input monitoring". I re-installed again but I'm not able to launch it after the double click. Any idea?

**Comment by baronlior** [comment]
I have needed to delete the Scroll Reverser entries on both `Accessibility` and `Import Monitoring`, then add it again - and only then it worked. 

Now it is working, on Catalina 10.15.2 (19C57)

**Comment by chocoboABC** [comment]
It worked for me too.

**Comment by jwvanderbeck** [comment]
Strangely this was working fine for me for several months (since last October based on my previous comment) but today it was broken again.  Removing it from Input Monitoring like @baronlior  said, then re-adding it fixed it.  I was unable to remove it from Accessibility for some reason (the check box would not un check) but I apparently didn't need to do that one.

So tl;dr if it is working then suddenly stops working, try quiting Scroll Reverser, then going into Security & Privacy -> Input Monitoring and literally just uncheck Scroll Reverse, then re-check it and then restart Scroll Reverser.

**Comment by bitbot-jon** [comment]
Similarly, Scroll Reverser was working fine for me for months on Catalina 10.15.2. In the past few days, the same issue happened to me where the trackpad scroll direction inherited the reversal (when the setting is disabled in m preferences for the trackpad).

I tried following the steps @jwvanderbeck outlined (Security & Privacy -> Input Monitoring) and disabled, re-enabled the checkmark. Unfortunately for me it did not address the issue.

As I attempted to further troubleshoot, I removed this permission request altogether (clicking the lock, then the minus sign), hoping I could re-add it. Unfortunately now it doesn't show, doesn't  give me the ability to add it back, and deleting the app from the Applications folder and re-adding it doesn't bring the setting back.

![image](https://user-images.githubusercontent.com/5440604/74064959-a2a0c500-49a8-11ea-8b19-6ec54814b148.png)


So I'm still facing the same issue of the trackpad not working, and not sure how to "reset" the app's settings or troubleshoot further.

**Comment by bitbot-jon** [comment]
As an update for anyone else experiencing this issue, I remembered a few days ago I enabled the "Zoom" feature in Mac OS's accessibility options (Fn-Option-Command-F5). This was the issue, and clearly messes with Scroll Reverser's ability to manipulate trackpad inputs.

Disabling the Zoom accessibility feature made the Reverse Trackpad checkbox function as expected and addressed the issue.

<img width="398" alt="Screen Shot 2020-02-07 at 5 48 05 PM" src="https://user-images.githubusercontent.com/5440604/74077165-68e4b400-49d2-11ea-8066-9b757b32a23b.png">

**Comment by webdeveloperpr** [comment]
I didn't realize how much I cared about this feature. I will NEVER upgrade my mac again.

**Comment by andyljones** [comment]
Had the same issue. What worked for me in the end was

  * remove Scroll Reverser from both Accessibility and Input Monitoring
  * remove Scroll Reverser from the Applications dir (aka uninstalling it)
  * redownload Scroll Reverser
  * reinstall Scroll Reverser (aka unzip it and stick it in the Applications dir)
  * add it back to the Accessibility and Input Monitoring lists
  * open the app. Success! 

Lord knows what the critical steps in there are. This is somewhere between 'turn it off and on again' and slaughtering goats.

**Comment by mrhieu** [comment]
> Had the same issue, and simply unticking/ticking the permissions didn't help. What worked for me in the end was
> 
> * remove Scroll Reverser from both Accessibility and Input Monitoring
> * remove Scroll Reverser from the Applications dir (aka uninstalling it)
> * redownload Scroll Reverser
> * reinstall Scroll Reverser (aka unzip it and stick it in the Applications dir)
> * add it back to the Accessibility and Input Monitoring lists
> * open the app. Success!
> 
> Lord knows what the critical steps in there are. This is somewhere between 'turn it off and on again' and reading chicken entrails.

This saved my day! Thanks @andyljones

**Comment by efluon** [comment]
> As an update for anyone else experiencing this issue, I remembered a few days ago I enabled the "Zoom" feature in Mac OS's accessibility options (Fn-Option-Command-F5). This was the issue, and clearly messes with Scroll Reverser's ability to manipulate trackpad inputs.

thanks for that, unfortunately the trackpad zoom is the least offensive (especially compared to ctrl + scroll, which is the next best), and I need zoom to work. I fear it is time to let go of separate mouse and trackpad and get a magic mouse. :(
