### ISSUE TITLE
cant open it any more; 

### ISSUE THREAD

**Issue by qiaoqiao10001** [pilotmoon/Scroll-Reverser#71]
I download it , unzip it   , and drop it to applications; but when I open it,  it can not open ;

**Comment by qiaoqiao10001** [comment]
macbookpro macos 10.14.5

**Comment by paulsroufe** [comment]
Same problem here, happened after the 10.14.6 update.

**Comment by jafelds** [comment]
won't open after update to Catalina

**Comment by mikecole20** [comment]
I was able to solve this by fixing permission. Open "Security & Privacy" from Spotlight and make sure permission is enabled for both Input Monitoring and Accessibility. At some point during the Catalina upgrade, Scroll Reverser lost Accessibility permission, but the app crashes rather than notifying the user of the problem.

**Comment by shineceo97** [comment]
> I was able to solve this by fixing permission. Open "Security & Privacy" from Spotlight and make sure permission is enabled for both Input Monitoring and Accessibility. At some point during the Catalina upgrade, Scroll Reverser lost Accessibility permission, but the app crashes rather than notifying the user of the problem.

You saved my life..
for my case, I delete all permission about that app, and added it again!

now it works!!

**Comment by weeeeeee** [comment]
segmentation fault

./Scroll\ Reverser 
2019-11-20 16:00:20.516 Scroll Reverser[786:8088] Scroll Reverser ready. Option-click the Scroll Reverser menu bar icon to show the debug console.
[1]    786 segmentation fault  ./Scroll\ Reverser

Already enable both [Input Monitoring] and [Accessibility] in [Security & Privacy]

ScrollReverser-1.7.6

macOS Catalina 10.15.1

**Comment by invariant** [comment]
Fixed in v1.8
