### ISSUE TITLE
pilotmoon.scroll-reverser PrefsReverseTrackpad

### ISSUE THREAD

**Issue by RobertClarke** [pilotmoon/Scroll-Reverser#72]
defaults write com.pilotmoon.scroll-reverser PrefsReverseTrackpad -bool false

Running this command in the terminal doesn't appear to change the "Scrolling Devices: Reverse Trackpad" bullion in the app.

**Comment by invariant** [comment]
It wouldn't update immediately. You'd need to quit Scroll Reverser, apply the default then restart Scroll Reverser.

**Comment by RobertClarke** [comment]
@invariant Have tried this. Doesn't appear to work

**Comment by invariant** [comment]
The key you want is ReverseTrackpad not PrefsReverseTrackpad

**Comment by RobertClarke** [comment]
That fixed it. Thanks!
