### ISSUE TITLE
requires keystrokes events permission

### ISSUE THREAD

**Issue by jagdishjadeja** [pilotmoon/Scroll-Reverser#83]
why does it requires keystrokes events?

**Comment by unstablectrl** [comment]
I also wasn't sure about this but I only allowed accessibility and it seems to be working as intended.

**Comment by invariant** [comment]
Scroll Reverser monitors gestures on the trackpad, which comes under the category of Input Monitoring. Scroll Reverser does not monitor keystrokes.

**Comment by charleshan** [comment]
I think this should become optional. Many people use scroll reverser to reverse scrolling for just the mouse.

**Comment by invariant** [comment]
If you don't need to distinguish between trackpad and mouse, then you can just set the scrolling direction directly in System Preferences.

**Comment by charleshan** [comment]
I was afraid that that might be the case. Thanks for the clarification.
