### ISSUE TITLE
can't work in catalina 10.15.5

### ISSUE THREAD

**Issue by tonglin0325** [pilotmoon/Scroll-Reverser#84]
<img width="1087" alt="图片" src="https://user-images.githubusercontent.com/17646435/85698048-e5232e00-b70c-11ea-8f4a-b5f984ac428f.png">

**Comment by mfn** [comment]
Please see https://github.com/pilotmoon/Scroll-Reverser/issues/75 , it might contain useful hints

**Comment by tonglin0325** [comment]
thx, it works when I enable it both in the Accessibility and Input Monitoring
<img width="568" alt="图片" src="https://user-images.githubusercontent.com/17646435/85716029-a1d1bb00-b71e-11ea-94f3-0ab2a67f580b.png">
