### ISSUE TITLE
Scroll Reverser app closes after iMac went to sleep (MacOS 11 beta 4)

### ISSUE THREAD

**Issue by Pobe16** [pilotmoon/Scroll-Reverser#87]
On 27" iMac mid 2017 (with upgrade to SSD and user-upgraded RAM).
Basically all in title - I am gathering more data and will come back to it.

**Comment by DungVA1** [comment]
I cannot open on MacOS 11 too :|

**Comment by iharkh** [comment]
![image](https://user-images.githubusercontent.com/6583990/95975836-5b17e600-0e1f-11eb-8d55-5196f2b617b6.png)

These are events in system console concerning Scroll Reverser right after system woke up from sleep. 
Maybe it will help.

**Comment by invariant** [comment]
Closing as duped by #90 and now fixed in master. Thanks for the early reporting of this, I'm afraid I wasn't on the ball enough to fix it before Big Sur shipped.
