### ISSUE TITLE
Any chance this great app will be working on Apple Silicon Macs?

### ISSUE THREAD

**Issue by wbrycki** [pilotmoon/Scroll-Reverser#89]

**Comment by invariant** [comment]
I estimate that there is a high chance of that.

**Comment by invariant** [comment]
My blog post: https://pilotmoon.com/blog/2020/11/11/bigsur-apple-silicon

**Comment by invariant** [comment]
Master branch is now Universal app now targeting Apple Silicon

**Comment by invariant** [comment]
Done in v1.8
