### ISSUE TITLE
Reverse 3 finger gestures?

### ISSUE THREAD

**Issue by invariant** [pilotmoon/Scroll-Reverser#9]
Ref: **[Conversation #1626](https://secure.helpscout.net/conversation/13303565/1626) / K. C.**

**Comment by invariant** [comment]
Won't implement.

**Comment by gregsdennis** [comment]
Can this conversation (or at least the pertinent portions) be replicated here so that users don't have to have a helpscout login to view it?  I think I'm experiencing a similar issue.

Also, (if this is the same issue I'm having) why wasn't it fixed?

**Comment by invariant** [comment]
The Help Scout link refers to a private email for my own reference. Here is the relevant excerpt:

> May I add a request? >> In Firefox: a 3 - finger vertical scroll will send one immediately to the top, or bottom of all webpages (amazingly handy); 3-finger left/right is page back/forward. So, yes, it's opposite with 3 fingers. Actually, I guess this covers 3-finger gestures globally

**Comment by invariant** [comment]
I can't comment on your issue since i don't know what it is, but here is a relevant excerpt from the [FAQ](https://pilotmoon.com/scrollreverser/):

> Can you make it reverse 3- and 4-finger swipes too? No, this is not possible.

**Comment by gregsdennis** [comment]
Well, I guess the fact that you can't do it makes my suggestion moot.  But I'll explain anyway.

A two-finger swipe will behave as one would expect from a touch screen, moving the content in the same direction as the swipe.  However, when changing Spaces using a three-finger swipe, the default behavior is opposite: swipe left to view the space to the left (moving the current screen to the right).

This is very confusing and I had hoped you application could resolve it, but it seems that this functionality is out of reach.

**Comment by invariant** [comment]
Unfortunately, yes it is. Gestures are implemented using a totally different system under the hood.

However, all you need to do is turn on "Scroll Direction: Natural" in trackpad preferences to get the behaviour you want.

You can then use Scroll Reverser to adjust scrolling separately (horizontal and/or vertical) if necessary.

**Comment by gregsdennis** [comment]
Thinking outside the box!  Nice.  That did the trick!
