### ISSUE TITLE
Big Sur: Scroll Reverser exits during system sleep

### ISSUE THREAD

**Issue by rgov** [pilotmoon/Scroll-Reverser#90]
# Please do not post "me too" comments on this issue!

I've been using Scroll Reverser 1.7.6 on Catalina without issue for a while. Since upgrading to Big Sur, when my system wakes up, scrolling is back to the default system behavior.

In the Console, at the same time that the system begins to sleep, I see these messages indicating that the program is exiting:

```
default	19:11:19.844279-0500	Scroll Reverser	NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 1
-appearance: (null)
-effectiveAppearance: <NSCompositeAppearance: 0x600002345880
 (
    "<NSAquaAppearance: 0x600002345780>",
    "<NSSystemAppearance: 0x600002344600>"
)>
default	19:11:20.345994-0500	kernel	PM response took 517 ms (89958, Scroll Reverser)
default	19:11:20.374226-0500	distnoted	register name: com.apple.nsquiet_safe_quit_give_reason object: com.pilotmoon.scroll-reverser token: 390000003d pid: 89958
default	19:12:09.489957-0500	Scroll Reverser	[logger "waiting for pid 89958"; while kill -0 89958 >/dev/null 2>&1; do sleep 0.01; done; logger "restarting Scroll Reverser"; open "/Applications/Scroll Reverser.app"]
default	19:12:09.645026-0500	Scroll Reverser	Entering exit handler.
default	19:12:09.652257-0500	Scroll Reverser	Exiting exit handler.
default	19:12:10.087100-0500	runningboardd	Calculated state for app<application.com.pilotmoon.scroll-reverser.8683812124.8683812163(501)>: none (role: None)
default	19:12:10.259541-0500	launchservicesd	Hit the server for a process handle 4ebe38700015f66 that resolved to: [app<application.com.pilotmoon.scroll-reverser.8683812124.8683812163(501)>:89958]
default	19:12:16.609355-0500	WindowServer	Add filter:IOHIDServiceFilter uuid:320990E6-DAAD-4738-A6F1-149766D2E167 name:com.apple.iokit.hid.IOHIDPointerScrollFilter  for service:0x1000590e6
```

Perhaps this issue is fixed in `master` since the last release was 3.5 years ago, but it has only become a problem for me now.

**Comment by rgov** [comment]
Same issue with `master`.

**Comment by FelixGraf** [comment]
I can confirm this issue on macOS BigSur 11.0.1 and ScrollReverser 1.7.6.

**Comment by lustasag** [comment]
> I can confirm this issue on macOS BigSur 11.0.1 and ScrollReverser 1.7.6.

Same here after the upgrade.

**Comment by JBYoshi** [comment]
Also having this problem - same versions.

**Comment by rgov** [comment]
Looks like the issue is confirmed. **Click the thumbs up 👍 above (under the first post) and use the Subscribe button on the right to get notified of updates.**

(Kindly don't post more "me too" comments.)

**Comment by vinsonma** [comment]
Also having this problem - same versions.

**Comment by vinsonma** [comment]
I can confirm this issue on macOS BigSur 11.0.1 and ScrollReverser 1.7.6.
![image](https://user-images.githubusercontent.com/40881873/99375304-8b5f1280-28fe-11eb-9a47-d8e7158f498c.png)
![image](https://user-images.githubusercontent.com/40881873/99375317-9023c680-28fe-11eb-9a57-f8ebf48b4a2c.png)

**Comment by politsin** [comment]
same

**Comment by rsha256** [comment]
I managed to temporarily fix this when my system sleeps from being idle by going into System Preferences → Security & Privacy → Privacy → Input Monitoring and giving it permission but after restarting, the issue persists, even though `Start at login` is checked, I think the startup script broke with MacOS Big Sur
![image](https://user-images.githubusercontent.com/28417128/99458058-eb9f8580-28f9-11eb-8a0e-12d2d8695ce5.png)

**Comment by saiftheboss7** [comment]
I can confirm the issue.

**Comment by sijianian** [comment]
Same issue.

**Comment by doortts** [comment]
I found a temporary work-around by using [ControlPlane App](https://www.controlplaneapp.com/)

![image](https://user-images.githubusercontent.com/520523/99623881-67234300-2a70-11eb-9f25-2a5d47b648e4.png)

![image](https://user-images.githubusercontent.com/520523/99623918-7bffd680-2a70-11eb-8216-0b69d6cfc3bb.png)

![image](https://user-images.githubusercontent.com/520523/99623930-8621d500-2a70-11eb-8543-b5abc18b33d1.png)

![image](https://user-images.githubusercontent.com/520523/99623946-9043d380-2a70-11eb-9868-7caae07aeb21.png)

**Comment by invariant** [comment]
Reopening issue for visibility until release build ships.

**Comment by invariant** [comment]
Testing build: https://github.com/pilotmoon/Scroll-Reverser/releases/tag/v1.8-beta.1

**Comment by rgov** [comment]
After a sleep-wake cycle test, I can confirm that the issue is resolved.
