### ISSUE TITLE
Add "Start at login" preference

### ISSUE THREAD

**Issue by SandersWen** [pilotmoon/Scroll-Reverser#93]
Does not start automatically after Mac reboot

**Comment by c-bandy** [comment]
As a workaround you can add it to your login items in `System Preferences > Users & Groups > Login Items`
![Screenshot 2020-11-20 at 12 33 55](https://user-images.githubusercontent.com/31383109/99795861-c5156080-2b2c-11eb-9853-b15a230fc912.png)

**Comment by invariant** [comment]
Thank you @c-bandy — this is the recommended approach. Works on all version of macOS. I'm renaming this issue as a placeholder for this feature request.

**Comment by invariant** [comment]
Haha, I forgot v1.7.8 already has Start at Login preference! It's not there in current master branch. I had removed it because of the reported problems with unreliability.
