### ISSUE TITLE
Could not enable on 1.8-beta.2

### ISSUE THREAD

**Issue by interestingdev** [pilotmoon/Scroll-Reverser#94]
Check the enable box failed.
OS version: 10.15.5 (19F101)

**Comment by invariant** [comment]
Thanks for reporting. Could you possibly record a short screen video (with QuickTime Player or similar) showing it happening? Post here it to my email support@pilotmoon.com

**Comment by interestingdev** [comment]
> Thanks for reporting. Could you possibly record a short screen video (with QuickTime Player or similar) showing it happening? Post it here or to my email support@pilotmoon.com
> […](#)
> Sent from my iPhone
> On 26 Nov 2020, at 00:19, DeYu Wu ***@***.***> wrote: ﻿ Check the enable box failed — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
