### ISSUE TITLE
Can you please update homebrew

### ISSUE THREAD

**Issue by elgs** [pilotmoon/Scroll-Reverser#95]
https://github.com/pilotmoon/Scroll-Reverser/issues/90

Since it's fixed in a new version mentioned in the thread above, can you please push it to homebrew? Thanks.

**Comment by invariant** [comment]
Still in beta. However, the homebrew release is nothing to do with me, in fact this is the first I knew about it!

**Comment by elgs** [comment]
Thank you so much. Now I got the update from homebrew, and everything works!

**Comment by invariant** [comment]
That’s great. I looked into it and it seems the homebrew cask updates automatically based on Scroll Reverser’s own Sparkle appcast feed, which is handy.
